---
addons:
  - name: "integreatly-operator"
    bundle:
      repo: "https://github.com/integr8ly/integreatly-operator.git"
      path: "bundles/integreatly-operator"
    channels:
      - name: "stage"
        directory: "integreatly-operator"
        environment: "stage"
        allow_pre_release: true
      - name: "edge"
        directory: "integreatly-operator-internal"
        environment: "production"
        allow_pre_release: false
      - name: "stable"
        directory: "integreatly-operator"
        environment: "production"
        allow_pre_release: false
    override:
      deployment:
        name: "rhmi-operator"
        container:
          name: "rhmi-operator"
          env_vars:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTALLATION_TYPE
              value: managed
            - name: OPERATOR_NAME
              value: rhmi-operator
            - name: LOG_LEVEL
              value: info
