---
addons:
  - name: "managed-api-service"
    bundle:
      repo: "https://github.com/integr8ly/integreatly-operator.git"
      path: "bundles/managed-api-service"
    channels:
      - name: "stage"
        directory: "rhoams"
        environment: "stage"
        allow_pre_release: true
      - name: "edge"
        directory: "managed-api-service-internal"
        environment: "production"
        allow_pre_release: false
      - name: "stable"
        directory: "rhoams"
        environment: "production"
        allow_pre_release: false
    override:
      deployment:
        name: "rhmi-operator"
        container:
          name: "rhmi-operator"